/* البيانات الأولية (seed) — مستخرجة من App.tsx */
import type {
  UserItem,
  FeeAgreement,
  PaymentReceipt,
  Client,
  CaseItem,
  Hearing,
  TaskItem,
  Invoice,
  DocItem,
  PoaItem,
  KycItem,
  KycWatchlistItem,
  NotificationLog,
  TimeLog,
  CaseExpense,
  TrustTransaction,
  JudgmentDeadline,
  InvoiceInstallment,
  StrReport,
  Employee,
  LeaveRequest,
  EmployeeExpense,
  AuditLogEntry,
  LegalPrecedent,
  InternalPolicy,
} from "./types";
import { ROLE_PRESETS } from "./permissions";
import { uaeTerroristList } from "../data/uaeTerroristListData";
import type { BookingRecord } from "../components/PublicConsultationPage";

export const seedUsers: UserItem[] = [
  {
    id: 1,
    name: "سعود أحمد الشحي",
    email: "info@lawyersuood.com",
    phone: "0501234567",
    password: "123456",
    roleTitle: "محامٍ شريك / مدير النظام",
    roleKey: "admin",
    status: "نشط",
    avatarBg: "bg-[#0c4a47]",
    avatarText: "سش",
    permissions: ROLE_PRESETS.admin.permissions,
    licenseNumber: "1754",
  },
];

export const seedFeeAgreements: FeeAgreement[] = [];

export const seedPayments: PaymentReceipt[] = [];

export const seedClients: Client[] = [
  {
    id: 101,
    name: "فوزية احمد عتيق علي المهيري",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 102,
    name: "خط السماء لصناعة عوادم السيارات- مؤسسة فردية",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 103,
    name: "دار سمرا للكمبيوتر ذ.م.م Dar Samra Computer L.L.C",
    type: "شركة",
    idNo: "100331456200003",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
    taxNo: "100331456200003",
  },
  {
    id: 104,
    name: "بريدج لخدمات الترجمة القانونية",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 105,
    name: "PAKIZA PROPERTIES L.L.C باكيزا للعقارات ش.ذ.م.م",
    type: "شركة",
    idNo: "105100974200003",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
    taxNo: "105100974200003",
  },
  {
    id: 106,
    name: "JOAN DAYAN CASTILLO",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "PH",
    address: "الفلبين",
  },
  {
    id: 107,
    name: "ابو بكر عبدالعزيز طلحة",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "SD",
    address: "السودان",
  },
  {
    id: 108,
    name: "Anthropic, PBC",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 109,
    name: "محمد سلطان الشامسي",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 110,
    name: "احمد مختار عيد محمد",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "EG",
    address: "مصر",
  },
  {
    id: 111,
    name: "aly mohsmed aly mohamed rehan",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "EG",
    address: "مصر",
  },
  {
    id: 112,
    name: "بنك المارية المحلي",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 113,
    name: "بوابة الابتكار للحلول التكنولوجية",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 114,
    name: "شما جمال عبدالله سالم السويدي shamma jamal abdalla salim alsuwaidi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "shammaalsuwaidi5555@outlook.com",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 115,
    name: "هونج كونج لتجارة أدوات التجميل ش.ذ.م.م HONG KONG COSMETICS TRADING L.L.C",
    type: "شركة",
    idNo: "104912672300003",
    phone: "",
    email: "hkcosmetics.pro@gmail.com",
    emirate: "AE",
    address: "الإمارات",
    taxNo: "104912672300003",
  },
  {
    id: 116,
    name: "الاوائل لصناعة البلاستك ذ.م.م Al-Awail Plastic Manufacturing LLC",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "Alawaelplasticindustry@gmail.com",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 117,
    name: "محمد صدام محمد نواز Muhammad Saddam Muhammad Nawaz",
    type: "فرد",
    idNo: "",
    phone: "0501043543",
    email: "sadamnawaz23006@gmail.com",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 118,
    name: "Day to day",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 119,
    name: "دار القضاء الشارقة-Sharjah Court House",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 120,
    name: "مهند صالح- Muhannad Saleh",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "Mohaneds45@hotmail.com",
    emirate: "GB",
    address: "المملكة المتحدة",
  },
  {
    id: 121,
    name: "الأستاذ المحامي / هيثم احمد سيف العامري-Lawyer/Professor Haitham Ahmed Saif Al-Amri",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 122,
    name: "الصافي لتنقية مياه الشرب-Al Safi for drinking water purification",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 123,
    name: "الهيئة العامة للمعاشات-General Authority for Pensions",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 124,
    name: "الشوؤن القانونية في دبي-Legal Affairs in Dubai",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 125,
    name: "الهيئة الاتحادية للضرائب-Federal Tax Authority",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 126,
    name: "FEDERAL TAX AUTHORITY",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 127,
    name: "ارامكس- Aramex",
    type: "شركة",
    idNo: "100212963100003",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
    taxNo: "100212963100003",
  },
  {
    id: 128,
    name: "name.com",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 129,
    name: "GOOGEL",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 130,
    name: "وزارة الموارد البشرية والتوطين-Ministry of Human Resources and Emiratization",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 131,
    name: "احمد طلال اليمن- Ahmed Talal Yemen",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "LB",
    address: "لبنان",
  },
  {
    id: 132,
    name: "دائرة التنمية الاقتصادية بشارقة-Sharjah Department of Economic Development",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 133,
    name: "بخيته صالح راشد راشد المنصوري-Bakhita Saleh Rashid Rashid Al Mansouri",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 134,
    name: "Usk zinc industries",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "mohammadumer.khalid@hotmail.com",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 135,
    name: "Elin foodstuff treding",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 136,
    name: "PNP GLOBAL SUPPLY COMPANY LIMITED",
    type: "شركة",
    idNo: "",
    phone: "+84911330257",
    email: "michael.hua@pnpglobalsupply.com",
    emirate: "VN",
    address: "فيتنام",
  },
  {
    id: 137,
    name: "دائرة التنمية الاقتصادية الشارقة-Sharjah Department of Economic Development",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 138,
    name: "Sharjah Electricity & Water Authority",
    type: "جهة حكومية",
    idNo: "100394961500003",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
    taxNo: "100394961500003",
  },
  {
    id: 139,
    name: "محمد عمر بن خالد خالد بشير-Muhammad Omar bin Khalid Khalid Bashir",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "PK",
    address: "باكستان",
  },
  {
    id: 140,
    name: "نسرين انطونيوس ظاهر-Nasreen Antonios Daher",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "SY",
    address: "سوريا",
  },
  {
    id: 141,
    name: "خليفة محمد احمد بيبي الشحي Khalifa Mohammed Ahmed Bibi Al Shehhi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 142,
    name: "بدر سعيد راشد سعيد الحبسي-Badr Saeed Rashid Saeed Al Habsi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "رأس الخيمة",
    address: "رأس الخيمة",
  },
  {
    id: 143,
    name: "Wafeq FZ LLC (Main)",
    type: "شركة",
    idNo: "100584752800003",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
    taxNo: "100584752800003",
  },
  {
    id: 144,
    name: "METHAQ TAKAFUL INSURANCE COMPANY",
    type: "شركة",
    idNo: "100000232700003",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
    taxNo: "100000232700003",
  },
  {
    id: 145,
    name: "MINISTRY OF JUSTICE",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 146,
    name: "du",
    type: "شركة",
    idNo: "100001397700003",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
    taxNo: "100001397700003",
  },
  {
    id: 147,
    name: "محمد احمد عبيد بن جرش الفلاسي-Mohammed Ahmed Obeid between Jarash Al-Fals",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "M.falasi87@gmail.com",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 148,
    name: "ناعومي كمال الدين ظريف-Naomi Kamal El-Din Zarif",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 149,
    name: "عزة راشد سعيد ساعد الشميلي-Azza Rashid Saeed Saad Al-Shumaili",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 150,
    name: "محمد صالح-Muhammad Saleh",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 151,
    name: "مريم محمد راشد-Maryam Mohammed Rashid",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 152,
    name: "نور عماد الدين إبراهيم-Nour Emad El-Din Ibrahim",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 153,
    name: "USK METALS L L C",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 154,
    name: "زينب بنت عبدالله بن غلوم البلوشية-Zainab bint Abdullah bin Ghloum Al Balushi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 155,
    name: "خالد خليفة عبيد الغول-Khaled Khalifa Obaid Al-Ghul",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 156,
    name: "عمر مصطفى عيد محمد-Omar Mustafa Eid Muhammad",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 157,
    name: "عبدالله محمد عبدالله المازمي-Abdullah Mohammed Abdullah Al Mazmi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 158,
    name: "أمير حسين جواد اقاباباني-Amir Hussein Jawad Aghababani",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "IR",
    address: "إيران",
  },
  {
    id: 159,
    name: "عذاري سعيد محمد الظنحاني Adhari Saeed Mohammed Al Dhanhani",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 160,
    name: "يعقوب حسن أحمد البنا-Yaqub Hassan Ahmed Al-Banna",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 161,
    name: "علا تحسين عبدالرؤف الفارس-Alaa Tahseen Abdul Raouf Al-Fares",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "DM",
    address: "دومينيكا",
  },
  {
    id: 162,
    name: "نادية يونس عثمان- Nadia Younes Othman",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 163,
    name: "احمد راشد الشميلي- Ahmed Rashid Al-Shumaili",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 164,
    name: "امينة آل بيات Amina Al-Bayat",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 165,
    name: "عمر مصطفى عيد محمد (تابي ) Omar Mustafa Eid Muhammad (Tabi)",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 166,
    name: "خالد بشير أوان محمد بشير اختر Khaled Bashir Awan Mohammed Bashir Akhtar",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "PK",
    address: "باكستان",
  },
  {
    id: 167,
    name: "إبراهيم محسن قاسم عبدالله Ibrahim Mohsen Qasim Abdullah",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دولي",
    address: "دولي",
  },
  {
    id: 168,
    name: "شركة دو  Du company",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 169,
    name: "sewa",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 170,
    name: "فاروق احمد غلام اكبر-Farooq Ahmed Ghulam Akbar",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "PK",
    address: "باكستان",
  },
  {
    id: 171,
    name: "ياروسلافا زولينا Yaroslava Zolina",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "UA",
    address: "أوكرانيا",
  },
  {
    id: 172,
    name: "راشد خميس فايز خميس مبارك-Rashid Khamis Fayez Khamis Mubarak",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 173,
    name: "محمد عبدالقادر سليمان حامد Mohammed Abdul Qader Suleiman Hamed",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "JO",
    address: "الأردن",
  },
  {
    id: 174,
    name: "صلاح حسين حسن تهلك Salah Hussein Hassan perished",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 175,
    name: "خميس سعيد سااعد الحبسي Khamis Saeed Saad Al Habsi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 176,
    name: "كمال سالم راشد اليماحي Kamal Salem Rashid Al-Yamahi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 177,
    name: "محمد خليفة عبدالله جاسم Mohammed Khalifa Abdullah Jassim",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 178,
    name: "كمال موسي حبيب حسن اليوسف Kamal Moussa Habib Hassan Al-Youssef",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 179,
    name: "محمود محمد غلاونجي Mahmoud Muhammad Ghalaounji",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "EG",
    address: "مصر",
  },
  {
    id: 180,
    name: "شيماء سعيد راشد ساعد الحبسي-Shaima Saeed Rashid Saad Al Habsi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 181,
    name: "سامي محروس عبدالغني مشعل-Sami Mahrous Abdelghani Mashal",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "EG",
    address: "مصر",
  },
  {
    id: 182,
    name: "رافي اكوب قره بتيان-Rafi Akop Karabetian",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "LB",
    address: "لبنان",
  },
  {
    id: 183,
    name: "وزارة العدل- Ministry of Justice",
    type: "جهة حكومية",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 184,
    name: "مؤسسة رواد-Pioneers Foundation",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 185,
    name: "عبدالله الرستماني للعقارات-Abdullah Al Rostamani Real Estate",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 186,
    name: "إبراهيم علي عباس بيشوه البلوشي-Ibrahim Ali Abbas Bishouh Al-Balushi",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "AE",
    address: "الإمارات",
  },
  {
    id: 187,
    name: "احمد حسن حسنى كامل جاويش",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 188,
    name: "جوناتهان جارفين ديميسا",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 189,
    name: "ورده مبارك سالم بن زوبع",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 190,
    name: "اطلانتس للمطابخ ش.ذ.م.م",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 191,
    name: "ميس منذر سعد الدين غوشه",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 192,
    name: "وصال عثمان محمد على",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 193,
    name: "سيروس مالك هاميلتون",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 194,
    name: "محمد صلاح السيد محمد قنديل",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 195,
    name: "شاه ايران سيد وهاب",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "رأس الخيمة",
    address: "رأس الخيمة",
  },
  {
    id: 196,
    name: "شاما خالد عوان خالد بشير",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "عجمان",
    address: "عجمان",
  },
  {
    id: 197,
    name: "شركة بختوار جنرال تريدنج",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "عجمان",
    address: "عجمان",
  },
  {
    id: 198,
    name: "محمد بن حيدر بن حسن الاخضر",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "عجمان",
    address: "عجمان",
  },
  {
    id: 199,
    name: "الشركة العالمية للسيارات والمعدات ايمكو المحدودة",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 200,
    name: "المامون للاستيراد والتصدير - مؤسسة فردية - يمثلها حسن على حسن يملوه",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 201,
    name: "عبد العزيز طلحة على محمد",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 202,
    name: "وفاء اسماعيل مبارك الشريف",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "كلباء - الشارقة",
  },
  {
    id: 203,
    name: "عدنان احمد صوفان",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 204,
    name: "موزه احمد راشد عبدالله الشامسى",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 205,
    name: "مصطفى صالح رزق السبول",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 206,
    name: "بانيبال سارجيزي",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 207,
    name: "محمد احمد لفلاسي",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 208,
    name: "عمر خالد",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "رأس الخيمة",
    address: "رأس الخيمة",
  },
  {
    id: 209,
    name: "نوف",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "الشارقة",
    address: "الشارقة",
  },
  {
    id: 210,
    name: "دي تي سي للتجارة العامة ش.ذ.م.م",
    type: "شركة",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
  {
    id: 211,
    name: "شهرام عابدى",
    type: "فرد",
    idNo: "",
    phone: "",
    email: "",
    emirate: "دبي",
    address: "دبي",
  },
];

export const seedCases: CaseItem[] = [
  {
    id: 201,
    number: "565/2026",
    clientId: 135, // ايلين لتجارة المواد الغذائية (ش.ذ.م.م)
    opponents: [],
    type: "تجاري",
    court: "محكمة الاستئناف المدنية عجمان",
    judge: "",
    status: "منتهية",
    subject: "المحكمة الاستئنافية المدنية - تجاري -",
    openDate: "",
    fee: 0,
  },
  {
    id: 202,
    number: "72/2026",
    clientId: 153, // يو اس كية للمعادن ذ.م.م خالد بشير اوان محمد بشير اختر
    opponents: [],
    type: "تجاري",
    court: "محكمة أم القيوين الاتحادية المحكمة الاستئنافية المدنية",
    judge: "",
    status: "منتهية",
    subject: "المحكمة الاستئنافية المدنية - تجاري -",
    openDate: "",
    fee: 0,
  },
  {
    id: 203,
    number: "1324/2025",
    clientId: 156, // عمر مصطفى عيد محمد
    opponents: [],
    type: "أحوال شخصية",
    court: "محكمة عجمان الاستئنافية الشرعية",
    judge: "",
    status: "منتهية",
    subject: "المحكمة الاستئنافية الشرعية - الأحوال الشخصية - (دعوى نسب اثبات / انكار)",
    openDate: "",
    fee: 0,
  },
  {
    id: 204,
    number: "1032 / 2025",
    clientId: 187, // احمد حسن حسنى كامل جاويش
    opponents: [],
    type: "مدني",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف مدني",
    openDate: "",
    fee: 0,
  },
  {
    id: 205,
    number: "925 / 2025",
    clientId: 182, // رافى اكوب قره بتيان
    opponents: [],
    type: "تنفيذي",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف تنفيذ تجاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 206,
    number: "357 / 2024",
    clientId: 188, // جوناتهان جارفين ديميسا
    opponents: [],
    type: "تجاري",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف تجاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 207,
    number: "282 / 2024",
    clientId: 189, // ورده مبارك سالم بن زوبع
    opponents: [],
    type: "عقاري",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف عقاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 208,
    number: "92 / 2024",
    clientId: 190, // اطلانتس للمطابخ ش.ذ.م.م
    opponents: [],
    type: "تجاري",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "التماس إعادة نظر تجاري-استئناف",
    openDate: "",
    fee: 0,
  },
  {
    id: 209,
    number: "286 / 2024",
    clientId: 182, // رافى اكوب قره بتيان
    opponents: [],
    type: "أمر أداء",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف أمر أداء",
    openDate: "",
    fee: 0,
  },
  {
    id: 210,
    number: "1475 / 2023",
    clientId: 191, // ميس منذر سعد الدين غوشه
    opponents: [],
    type: "أحوال شخصية",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف احوال شخصية ومواريث",
    openDate: "",
    fee: 0,
  },
  {
    id: 211,
    number: "1447 / 2023",
    clientId: 191, // ميس منذر سعد الدين غوشه
    opponents: [],
    type: "أحوال شخصية",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف احوال شخصية ومواريث",
    openDate: "",
    fee: 0,
  },
  {
    id: 212,
    number: "436 / 2022",
    clientId: 192, // وصال عثمان محمد على
    opponents: [],
    type: "أمر أداء",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف أمر أداء",
    openDate: "",
    fee: 0,
  },
  {
    id: 213,
    number: "470 / 2020",
    clientId: 192, // وصال عثمان محمد على
    opponents: [],
    type: "أمر أداء",
    court: "محكمة الاستئناف دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف أمر أداء",
    openDate: "",
    fee: 0,
  },
  {
    id: 214,
    number: "1211/2025",
    clientId: 164, // امينه ال بيات
    opponents: [],
    type: "مدني",
    court: "محكمة الشارقة الاستئنافية المدنية",
    judge: "",
    status: "منتهية",
    subject: "المحكمة الاستئنافية المدنية - مدني",
    openDate: "",
    fee: 0,
  },
  {
    id: 215,
    number: "1862/2025",
    clientId: 193, // سيروس مالك هاميلتون
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف الجنح",
    openDate: "",
    fee: 0,
  },
  {
    id: 216,
    number: "1543/2024",
    clientId: 187, // احمد حسن حسنى كامل جاويش
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف الجنح",
    openDate: "",
    fee: 0,
  },
  {
    id: 217,
    number: "7362/2022",
    clientId: 194, // محمد صلاح السيد محمد قنديل
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح دبي",
    judge: "",
    status: "منتهية",
    subject: "استئناف الجنح",
    openDate: "",
    fee: 0,
  },
  {
    id: 218,
    number: "1584/2026",
    clientId: 166, // خالد بشير اوان محمد بشير اختر
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح عجمان",
    judge: "",
    status: "منتهية",
    subject: "استئناف الجنح",
    openDate: "",
    fee: 0,
  },
  {
    id: 219,
    number: "806/2025",
    clientId: 156, // عمر مصطفي عيد محمد
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح عجمان",
    judge: "",
    status: "منتهية",
    subject: "استئناف الجنح",
    openDate: "",
    fee: 0,
  },
  {
    id: 220,
    number: "160/2025",
    clientId: 149, // عزه
    opponents: [],
    type: "أحوال شخصية",
    court: "محكمة رأس الخيمة الاستئنافية الشرعية",
    judge: "",
    status: "منتهية",
    subject: "استئناف الاحوال الشخصية",
    openDate: "",
    fee: 0,
  },
  {
    id: 221,
    number: "816/2024",
    clientId: 170, // فاروق احمد غلام اكبر
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح رأس الخيمة",
    judge: "",
    status: "منتهية",
    subject: "استئناف جزاء",
    openDate: "",
    fee: 0,
  },
  {
    id: 222,
    number: "852/2024",
    clientId: 195, // شاه ايران سيد وهاب
    opponents: [],
    type: "جزائي",
    court: "محكمة استئناف الجنح رأس الخيمة",
    judge: "",
    status: "منتهية",
    subject: "استئناف جزاء",
    openDate: "",
    fee: 0,
  },
  {
    id: 223,
    number: "783/2026",
    clientId: 196, // شاما خالد عوان خالد بشير
    opponents: [],
    type: "تجاري",
    court: "محكمة الاستئناف المدنية عجمان",
    judge: "",
    status: "منتهية",
    subject: "المحكمة الاستئنافية المدنية - تجاري - مطالبات مالية",
    openDate: "",
    fee: 0,
  },
  {
    id: 224,
    number: "84/2026",
    clientId: 153, // يو اس كية للمعادن ذ.م.م -خالد بشير
    opponents: [],
    type: "تجاري",
    court: "محكمة أم القيوين الاتحادية المحكمة الاستئنافية المدنية",
    judge: "",
    status: "منتهية",
    subject: "المحكمة الاستئنافية المدنية - تجاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 301,
    number: "2026/450",
    clientId: 197,
    opponents: [],
    type: "منازعة التنفيذ الموضوعية",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "منازعة التنفيذ الموضوعية",
    openDate: "",
    fee: 0,
  },
  {
    id: 302,
    number: "2026/240",
    clientId: 153,
    opponents: [],
    type: "منازعة التنفيذ الموضوعية",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "منازعة التنفيذ الموضوعية",
    openDate: "",
    fee: 0,
  },
  {
    id: 303,
    number: "2026/241",
    clientId: 153,
    opponents: [],
    type: "منازعة التنفيذ الموضوعية",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "منازعة التنفيذ الموضوعية",
    openDate: "",
    fee: 0,
  },
  {
    id: 304,
    number: "2026/322",
    clientId: 197,
    opponents: [],
    type: "تجاري - البنوك",
    court: "محكمة عجمان المدنية الاتحادية",
    judge: "",
    status: "متداولة",
    subject: "تجاري - البنوك",
    openDate: "",
    fee: 0,
  },
  {
    id: 305,
    number: "2025/481",
    clientId: 153,
    opponents: [],
    type: "منازعة التنفيذ الموضوعية",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "منازعة التنفيذ الموضوعية",
    openDate: "",
    fee: 0,
  },
  {
    id: 306,
    number: "2025/5881",
    clientId: 135,
    opponents: [],
    type: "محكمة التنفيذ المدنية - تجاري - مطالبات مالية",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - تجاري - مطالبات مالية",
    openDate: "",
    fee: 0,
  },
  {
    id: 307,
    number: "2025/881",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة - الوفاء الكلي",
    court: "محكمة أم القيوين",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة - الوفاء الكلي",
    openDate: "",
    fee: 0,
  },
  {
    id: 309,
    number: "2026/242",
    clientId: 153,
    opponents: [],
    type: "منازعة التنفيذ الموضوعية",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "منازعة التنفيذ الموضوعية",
    openDate: "",
    fee: 0,
  },
  {
    id: 310,
    number: "2026/514",
    clientId: 196,
    opponents: [],
    type: "المحكمة الابتدائية المدنية - تجاري - البنوك",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية المدنية - تجاري - البنوك",
    openDate: "",
    fee: 0,
  },
  {
    id: 311,
    number: "2024/3909",
    clientId: 160,
    opponents: [],
    type: "المحكمة الابتدائية المدنيه - أمر على عريضة",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية المدنيه - أمر على عريضة",
    openDate: "",
    fee: 0,
  },
  {
    id: 312,
    number: "2025/566",
    clientId: 198,
    opponents: [],
    type: "الدائرة المدنية والتجارية والعمالية",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "الدائرة المدنية والتجارية والعمالية",
    openDate: "",
    fee: 0,
  },
  {
    id: 313,
    number: "2025/569",
    clientId: 198,
    opponents: [],
    type: "الدائرة المدنية والتجارية والعمالية والإدارية ودعاوي الملكية الفكرية",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "الدائرة المدنية والتجارية والعمالية والإدارية ودعاوي الملكية الفكرية",
    openDate: "",
    fee: 0,
  },
  {
    id: 314,
    number: "2025/568",
    clientId: 198,
    opponents: [],
    type: "الدائرة المدنية والتجارية والعمالية والإدارية ودعاوي الملكية الفكرية",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "الدائرة المدنية والتجارية والعمالية والإدارية ودعاوي الملكية الفكرية",
    openDate: "",
    fee: 0,
  },
  {
    id: 315,
    number: "2025/1205",
    clientId: 156,
    opponents: [],
    type: "المحكمة الابتدائية الشرعية - الأحوال الشخصية - دعوى نسب (اثبات / انكار)",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية الشرعية - الأحوال الشخصية - دعوى نسب (اثبات / انكار)",
    openDate: "",
    fee: 0,
  },
  {
    id: 316,
    number: "2026/3",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 317,
    number: "2024/127",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 318,
    number: "2024/2393",
    clientId: 197,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 319,
    number: "2025/6",
    clientId: 160,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 320,
    number: "2025/93",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 321,
    number: "2024/3911",
    clientId: 160,
    opponents: [],
    type: "دائرة الدعاوي المستعجلة والأوامر على عرائض",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "دائرة الدعاوي المستعجلة والأوامر على عرائض",
    openDate: "",
    fee: 0,
  },
  {
    id: 322,
    number: "2026/38",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 323,
    number: "2026/73",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 324,
    number: "2026/52",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 325,
    number: "2026/1360",
    clientId: 135,
    opponents: [],
    type: "محكمة التنفيذ المدنية - منازعة التنفيذ الموضوعية",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - منازعة التنفيذ الموضوعية",
    openDate: "",
    fee: 0,
  },
  {
    id: 326,
    number: "2023/795",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 327,
    number: "2024/320",
    clientId: 197,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة عجمان الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 328,
    number: "2026/211",
    clientId: 153,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 329,
    number: "2026/219",
    clientId: 197,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة أم القيوين - دائرة التنفيذ الأولى",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 330,
    number: "2025/0002112",
    clientId: 197,
    opponents: [],
    type: "الأحوال الشخصية لغير المسلمين - دعوى طلاق (للضرر)",
    court: "محكمة الشارقة الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "الأحوال الشخصية لغير المسلمين - دعوى طلاق (للضرر)",
    openDate: "",
    fee: 0,
  },
  {
    id: 331,
    number: "2025/0000172",
    clientId: 197,
    opponents: [],
    type: "المحكمة الابتدائية الشرعية - تظلم",
    court: "محكمة الشارقة الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية الشرعية - تظلم",
    openDate: "",
    fee: 0,
  },
  {
    id: 332,
    number: "2025/7445",
    clientId: 141,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "محكمة الشارقة الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 333,
    number: "2025/3529",
    clientId: 199,
    opponents: [],
    type: "المحكمة الابتدائية المدنيه - تجاري",
    court: "دائرة الملكية الفكرية الشارقة",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية المدنيه - تجاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 334,
    number: "2025/0001237",
    clientId: 150,
    opponents: [],
    type: "المحكمة الابتدائية الشرعية - الأحوال الشخصية - دعوى طلاق (للضرر)",
    court: "محكمة الشارقة الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية الشرعية - الأحوال الشخصية - دعوى طلاق (للضرر)",
    openDate: "",
    fee: 0,
  },
  {
    id: 335,
    number: "2025/114",
    clientId: 150,
    opponents: [],
    type: "المحكمة الابتدائية الشرعية - تظلم",
    court: "محكمة الشارقة الابتدائية",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية الشرعية - تظلم",
    openDate: "",
    fee: 0,
  },
  {
    id: 336,
    number: "2025/4643",
    clientId: 164,
    opponents: [],
    type: "محكمة التنفيذ المدنية - عمالي",
    court: "دائرة التنفيذ العمالي السابعة الشارقة",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - عمالي",
    openDate: "",
    fee: 0,
  },
  {
    id: 337,
    number: "COM2019/0003542",
    clientId: 200,
    opponents: [],
    type: "محكمة التنفيذ المدنية - تجاري (كلي) - مطالبات مالية",
    court: "دائرة التنفيذ الثانية الشارقة",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - تجاري (كلي) - مطالبات مالية",
    openDate: "",
    fee: 0,
  },
  {
    id: 338,
    number: "2026/3331",
    clientId: 201,
    opponents: [],
    type: "المحكمة الابتدائية المدنيه - منازعة إيجارية - سكني",
    court: "لجنة فض المنازعات الشارقة",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية المدنيه - منازعة إيجارية - سكني",
    openDate: "",
    fee: 0,
  },
  {
    id: 339,
    number: "2023/15",
    clientId: 202,
    opponents: [],
    type: "المحكمة الابتدائية الشرعية - تظلم",
    court: "كلباء - دائرة الأحوال الشخصية الأولى",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية الشرعية - تظلم",
    openDate: "",
    fee: 0,
  },
  {
    id: 340,
    number: "2023/064",
    clientId: 202,
    opponents: [],
    type: "المحكمة الابتدائية الشرعية - أمر على عريضة - الأمور المستعجلة",
    court: "كلباء - دائرة الأمور المستعجلة",
    judge: "",
    status: "متداولة",
    subject: "المحكمة الابتدائية الشرعية - أمر على عريضة - الأمور المستعجلة",
    openDate: "",
    fee: 0,
  },
  {
    id: 341,
    number: "2023/2646",
    clientId: 203,
    opponents: [],
    type: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    court: "دائرة التنفيذ الثالثة الشارقة",
    judge: "",
    status: "متداولة",
    subject: "محكمة التنفيذ المدنية - الشيكات المرتجعة",
    openDate: "",
    fee: 0,
  },
  {
    id: 342,
    number: "2026/3760",
    clientId: 204,
    opponents: [],
    type: "حالات زوجية مسلمين",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "حالات زوجية مسلمين",
    openDate: "",
    fee: 0,
  },
  {
    id: 343,
    number: "2024/599",
    clientId: 187,
    opponents: [],
    type: "مدنى جزئى",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "مدنى جزئى",
    openDate: "",
    fee: 0,
  },
  {
    id: 344,
    number: "2023/1613",
    clientId: 205,
    opponents: [],
    type: "امر أداء",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "امر أداء",
    openDate: "",
    fee: 0,
  },
  {
    id: 345,
    number: "2023/46",
    clientId: 192,
    opponents: [],
    type: "منازعة موضوعية التنفيذ التجاري",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "منازعة موضوعية التنفيذ التجاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 346,
    number: "2024/984",
    clientId: 206,
    opponents: [],
    type: "عقاري",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "عقاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 347,
    number: "2025/19016",
    clientId: 147,
    opponents: [],
    type: "تنفيذ شيكات",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تنفيذ شيكات",
    openDate: "",
    fee: 0,
  },
  {
    id: 348,
    number: "2019/268",
    clientId: 152,
    opponents: [],
    type: "تنفيذ شرعي",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تنفيذ شرعي",
    openDate: "",
    fee: 0,
  },
  {
    id: 349,
    number: "2026/2726",
    clientId: 207,
    opponents: [],
    type: "منازعة ايجارية",
    court: "محاكم الشارقة",
    judge: "",
    status: "متداولة",
    subject: "منازعة ايجارية",
    openDate: "",
    fee: 0,
  },
  {
    id: 350,
    number: "2026/806",
    clientId: 208,
    opponents: [],
    type: "قضية",
    court: "محاكم رأس الخيمة",
    judge: "",
    status: "متداولة",
    subject: "دعوى قضائية",
    openDate: "",
    fee: 0,
  },
  {
    id: 351,
    number: "2026/397",
    clientId: 209,
    opponents: [],
    type: "طلاق للضرر",
    court: "محاكم الشارقة",
    judge: "",
    status: "متداولة",
    subject: "طلاق للضرر",
    openDate: "",
    fee: 0,
  },
  {
    id: 352,
    number: "2026/1062",
    clientId: 209,
    opponents: [],
    type: "طلاق للضرر",
    court: "محاكم الشارقة",
    judge: "",
    status: "متداولة",
    subject: "طلاق للضرر",
    openDate: "",
    fee: 0,
  },
  {
    id: 353,
    number: "2025/215",
    clientId: 161,
    opponents: [],
    type: "عقاري كلي",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "عقاري كلي",
    openDate: "",
    fee: 0,
  },
  {
    id: 354,
    number: "2025/196",
    clientId: 157,
    opponents: [],
    type: "تظلم شرعي",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تظلم شرعي",
    openDate: "",
    fee: 0,
  },
  {
    id: 355,
    number: "2025/355",
    clientId: 121,
    opponents: [],
    type: "امر أداء",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "امر أداء ياروسلافا زولينا",
    openDate: "",
    fee: 0,
  },
  {
    id: 356,
    number: "2025/32",
    clientId: 171,
    opponents: [],
    type: "تظلم من أمر أداء",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تظلم من أمر أداء ياروسلافا زولينا",
    openDate: "",
    fee: 0,
  },
  {
    id: 357,
    number: "2025/1546",
    clientId: 157,
    opponents: [],
    type: "احوال نفس مسلمين",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "احوال نفس مسلمين",
    openDate: "",
    fee: 0,
  },
  {
    id: 358,
    number: "2025/140",
    clientId: 182,
    opponents: [],
    type: "منازعة موضوعية تنفيذ شيكات",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "منازعة موضوعية تنفيذ شيكات",
    openDate: "",
    fee: 0,
  },
  {
    id: 359,
    number: "2023/555",
    clientId: 189,
    opponents: [],
    type: "عقاري",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "عقاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 360,
    number: "",
    clientId: 188,
    opponents: [],
    type: "تجاري",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تجاري",
    openDate: "",
    fee: 0,
  },
  {
    id: 361,
    number: "2023/1486",
    clientId: 191,
    opponents: [],
    type: "احوال نفس مسلمين",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "احوال نفس مسلمين",
    openDate: "",
    fee: 0,
  },
  {
    id: 364,
    number: "2025/584",
    clientId: 210,
    opponents: [],
    type: "منازعة موضوعية تنفيذ شيكات",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "منازعة موضوعية تنفيذ شيكات",
    openDate: "",
    fee: 0,
  },
  {
    id: 365,
    number: "2024/30121",
    clientId: 182,
    opponents: [],
    type: "تنفيذ شيكات",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تنفيذ شيكات",
    openDate: "",
    fee: 0,
  },
  {
    id: 366,
    number: "2025/18042",
    clientId: 211,
    opponents: [],
    type: "تنفيذ شيكات",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تنفيذ شيكات",
    openDate: "",
    fee: 0,
  },
  {
    id: 367,
    number: "2017/19",
    clientId: 161,
    opponents: [],
    type: "عرض وإيداع مدني",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "عرض وإيداع مدني",
    openDate: "",
    fee: 0,
  },
  {
    id: 368,
    number: "2019/5820",
    clientId: 171,
    opponents: [],
    type: "تنفيذ تجاري",
    court: "محاكم دبي",
    judge: "",
    status: "متداولة",
    subject: "تنفيذ تجاري",
    openDate: "",
    fee: 0,
  },
];

export const seedHearings: Hearing[] = [];

export const seedTasks: TaskItem[] = [];

export const seedInvoices: Invoice[] = [];

export const seedDocs: DocItem[] = [];

export const seedPoas: PoaItem[] = [];

export const seedKyc: KycItem[] = [];

export const seedKycWatchlist: KycWatchlistItem[] = uaeTerroristList;

export const seedNotifications: NotificationLog[] = [];

export const seedTimeLogs: TimeLog[] = [];

export const seedCaseExpenses: CaseExpense[] = [];

export const seedTrustTransactions: TrustTransaction[] = [];

export const seedDeadlines: JudgmentDeadline[] = [];

export const seedDeadlinesOld_unused: JudgmentDeadline[] = [
  {
    id: 1,
    caseId: 101,
    rulingDate: new Date(Date.now() - 27 * 86400000).toISOString().slice(0, 10),
    rulingType: "حكم ابتدائية",
    rulingSummary:
      "إلزام المدعى عليها بشركة النجم الذهبي بأن تؤدي للموكل مبلغ 850,000 درهم والفائدة 5% والرسوم.",
    appealDays: 30,
    appealDeadlineDate: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
    status: "جارٍ حساب الميعاد",
    notes: "مهلة استئناف عاجلة جداً — متبقي 3 أيام فقط لقيد الصحيفة بالمحكمة",
    assignedLawyerId: 1,
    assignedLawyerName: "المحامي سعود أحمد الشحي",
    assignedLawyerPhone: "0501234567",
    assignedLawyerEmail: "info@lawyersuood.com",
    preferredChannel: "both",
    alert7DaysSent: true,
    alert7DaysSentAt: new Date(Date.now() - 4 * 86400000).toLocaleDateString("ar-AE") + " 10:00 AM",
    alert3DaysSent: false,
    autoAlertLogs: [
      {
        id: "log-1",
        timestamp: new Date(Date.now() - 4 * 86400000).toLocaleDateString("ar-AE") + " 10:00 AM",
        type: "7_days",
        channel: "both",
        lawyerName: "المحامي سعود أحمد الشحي",
        recipientContact: "info@lawyersuood.com",
        status: "sent",
        messageSnippet:
          "⚠️ [تنبيه 7 أيام] تم إرسال إشعار استباقي أول للبريد الإلكتروني للتذكير بمهلة الاستئناف.",
      },
    ],
  },
  {
    id: 2,
    caseId: 102,
    rulingDate: new Date(Date.now() - 23 * 86400000).toISOString().slice(0, 10),
    rulingType: "حكم ابتدائية",
    rulingSummary:
      "رفض دعوى الإخلاء جزئياً وإلزام المستأجر بسداد المتأخرات فقط قدرها 120,000 درهم.",
    appealDays: 30,
    appealDeadlineDate: new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10),
    status: "جارٍ حساب الميعاد",
    notes: "مهلة طعن بالاستئناف بالشارقة — تجهيز صحيفة الاستئناف للمطالبة بالإخلاء",
    assignedLawyerId: 2,
    assignedLawyerName: "المحامي أحمد المزروعي",
    assignedLawyerPhone: "0509876543",
    assignedLawyerEmail: "ahmed.almazrouei@lawyersuood.com",
    preferredChannel: "both",
    alert7DaysSent: false,
    alert3DaysSent: false,
    autoAlertLogs: [],
  },
  {
    id: 3,
    caseId: 103,
    rulingDate: new Date(Date.now() - 12 * 86400000).toISOString().slice(0, 10),
    rulingType: "حكم ابتدائية",
    rulingSummary:
      "حكم عمالي بإلزام الشركة بمبلغ 45,000 درهم وبدل تذكرة عودة ومكافأة نهاية الخدمة.",
    appealDays: 30,
    appealDeadlineDate: new Date(Date.now() + 18 * 86400000).toISOString().slice(0, 10),
    status: "جارٍ حساب الميعاد",
    notes: "جارٍ التواصل مع الموكل لتحديد مدى الرغبة في الاستئناف أو التنفيذ المباشر",
    assignedLawyerId: 1,
    assignedLawyerName: "المحامي سعود أحمد الشحي",
    assignedLawyerPhone: "0501234567",
    assignedLawyerEmail: "info@lawyersuood.com",
    preferredChannel: "email",
    alert7DaysSent: false,
    alert3DaysSent: false,
    autoAlertLogs: [],
  },
  {
    id: 4,
    caseId: 104,
    rulingDate: new Date(Date.now() - 40 * 86400000).toISOString().slice(0, 10),
    rulingType: "حكم استئناف",
    rulingSummary: "قبول الاستئناف شكلاً وفي الموضوع بتعديل المبلغ إلى 320,000 درهم.",
    appealDays: 30,
    appealDeadlineDate: new Date(Date.now() - 10 * 86400000).toISOString().slice(0, 10),
    status: "تم تقديم الطعن",
    notes: "تم تمييز الحكم وقيد طعن التمييز برقم 112/2026 تمييز تجاري دبي",
    assignedLawyerId: 1,
    assignedLawyerName: "المحامي سعود أحمد الشحي",
    assignedLawyerPhone: "0501234567",
    assignedLawyerEmail: "info@lawyersuood.com",
    preferredChannel: "both",
    alert7DaysSent: true,
    alert3DaysSent: true,
    autoAlertLogs: [],
  },
];

export const seedInstallments: InvoiceInstallment[] = [];

export const seedStrReports: StrReport[] = [];

export const seedEmployees: Employee[] = [];

export const seedLeaveRequests: LeaveRequest[] = [];

export const seedEmployeeExpenses: EmployeeExpense[] = [];

export const seedAuditLogs: AuditLogEntry[] = [
  {
    id: "audit-1740000001",
    timestamp: "2026-08-23T08:30:15.120Z",
    formattedTimestamp: "23/08/2026 12:30:15 م",
    userId: 1,
    userName: "سعود بن عبد العزيز",
    userEmail: "info@lawyersuood.com",
    userRole: "مدير النظام",
    actionType: "DELETE",
    targetModule: "الأرشيف والمستندات",
    targetId: "doc-99",
    targetTitle: "مسودة لائحة دعوى مكررة",
    details:
      "تم تنفيذ وتأكيد حذف المستند نهائياً بعد التحقق من الصلاحيات وتأكيد نافذة التحذير الأمني.",
    ipAddress: "192.168.1.10",
    status: "مؤكد",
  },
  {
    id: "audit-1740000002",
    timestamp: "2026-08-23T09:14:42.550Z",
    formattedTimestamp: "23/08/2026 01:14:42 م",
    userId: 4,
    userName: "محامي متدرب",
    userEmail: "trainee@lawyersuood.com",
    userRole: "محامي متدرب",
    actionType: "UNAUTHORIZED_DELETE",
    targetModule: "إدارة القضايا",
    targetId: "case-102",
    targetTitle: "محاولة حذف القضية رقم 2026/410",
    details:
      "محاولة غير مصرح بها: حاول المستخدم (معرف ID: #4) تنفيذ [حذف ملف القضية] دون امتلاك الصلاحية المطلوبة [حذف القضايا والملفات]. تم حظر العملية وإحباطها تلقائياً وتنبيه المستخدم.",
    ipAddress: "192.168.1.45",
    status: "محاولة غير مصرح بها - مرفوض",
  },
];

export const seedConsultationBookings: BookingRecord[] = [];

export const seedLegalPrecedents: LegalPrecedent[] = [];

export const seedInternalPolicies: InternalPolicy[] = [];
