export const records451toEnd = [
  // Page 13: 451-468 (continuation)
  { id: 451, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "علي الشامسي", phone: "092015265", email: "aalshamsi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 452, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "جمال المازمي", phone: "092015245", email: "galmazmi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 453, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "سعيد النعيمي", phone: "092015252", email: "salnuaimi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 454, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "سيف آل علي", phone: "092015258", email: "salali@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 455, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "طارق عبدالحميد", phone: "092015260", email: "Tabdelhamid@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 456, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "عبدالله العبدولي", phone: "092015262", email: "aabdooli@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 457, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "محمد الحوسني", phone: "092015268", email: "malhosani@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 458, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "ياسر الهوتي", phone: "092015272", email: "yalhooti@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 459, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "يعقوب المازمي", phone: "092015275", email: "yalmazmi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 460, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "إسماعيل البلوشي", phone: "092015243", email: "Ialblooshi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 461, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الاستئناف", name: "سلطان آل علي", phone: "092015255", email: "salali@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 462, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر دائرة الجنح المستأنفة", name: "خالد المسماري", phone: "092015251", email: "kmesmari@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 463, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر دائرة الجنايات المستأنفة", name: "أحمد اليماحي", phone: "092015253", email: "aalyamahi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 464, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر دائرة الأحوال الشخصية المستأنفة", name: "حمدان الكعبي", phone: "092015254", email: "halkaabi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 465, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الدائرة العمالية المستأنفة", name: "سلطان الظنحاني", phone: "092015256", email: "sdhanhani@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 466, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الدائرة التجارية المستأنفة", name: "فيصل الحمودي", phone: "092015257", email: "falhamoudi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 467, court: "محكمة الفجيرة الاستئنافية", dept: "أمين سر الدائرة المدنية المستأنفة", name: "ماجد الصريدي", phone: "092015259", email: "msuraidi@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 468, court: "محكمة الفجيرة الاستئنافية", dept: "رئيس محكمة الاستئناف", name: "سعادة رئيس محكمة الاستئناف", phone: "092015247", email: "appeal.president.fuj@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },

  // Page 14: 469-497
  { id: 469, court: "محكمة الفجيرة الاستئنافية", dept: "سكرتارية رئيس محكمة الاستئناف", name: "عبدالله الكندي", phone: "092015249", email: "sec.appeal.fuj@moj.gov.ae", hours: "", loc: "الفجيرة", source: "ص1 02", em: "الفجيرة" },
  { id: 470, court: "محكمة حتا", dept: "مكتب المحكمة", name: "", phone: "048521232 / 048521025", email: "", hours: "", loc: "حتا - دبي", source: "11 ص27", em: "دبي" },
  { id: 471, court: "محكمة دبا الحصن الجزئية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "حمد الطنيجي", phone: "092053629", email: "Hmalteneiji@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 472, court: "محكمة دبا الحصن الجزئية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "سالم المرزوقي", phone: "092053611", email: "salmarzooqi@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 473, court: "محكمة دبا الحصن الجزئية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "سيف الطنيجي", phone: "092053640", email: "smalteneiji@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 474, court: "محكمة دبا الحصن الجزئية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "محمد الحوسني", phone: "092053644", email: "malhosani@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 475, court: "محكمة دبا الحصن الجزئية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "أحمد راشد", phone: "092053614", email: "amohamed@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 476, court: "محكمة دبا الحصن الجزئية", dept: "إدارة الدعوى", name: "خليفة الطنيجي", phone: "092053613", email: "kralteneiji@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 477, court: "محكمة دبا الحصن الجزئية", dept: "إدارة الدعوى", name: "سعيد الكتبي", phone: "092053633", email: "Smalketbi@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 478, court: "محكمة دبا الحصن الجزئية", dept: "إدارة الدعوى", name: "محمد مصبح", phone: "092053634", email: "mmalbedwawi@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 479, court: "محكمة دبا الحصن الجزئية", dept: "الإشراف الإداري", name: "سالم دغيش", phone: "092053619", email: "sdalteneiji@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 480, court: "محكمة دبا الحصن الجزئية", dept: "التنفيذ", name: "سالم الكتبي", phone: "092053635", email: "Sketbi@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 481, court: "محكمة دبا الحصن الجزئية", dept: "التنفيذ", name: "علي الشامسي", phone: "092053625", email: "ahalshamsi@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 482, court: "محكمة دبا الحصن الجزئية", dept: "التنفيذ", name: "محمد القايدي", phone: "092053615", email: "Malqaydi@moj.gov.ae", hours: "", loc: "دبا الحصن - الشارقة", source: "ص2 02", em: "الشارقة" },
  { id: 483, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "حمد الطنيجي", phone: "092045529", email: "Hmalteneiji@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 484, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "سالم المرزوقي", phone: "092045511", email: "salmarzooqi@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 485, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "سيف الطنيجي", phone: "092045540", email: "smalteneiji@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 486, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "محمد الحوسني", phone: "092045544", email: "malhosani@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 487, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "أمناء السر - مدني وتجاري وعمالي", name: "أحمد راشد", phone: "092045514", email: "amohamed@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 488, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "إدارة الدعوى", name: "خليفة الطنيجي", phone: "092045513", email: "kralteneiji@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 489, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "إدارة الدعوى", name: "سعيد الكتبي", phone: "092045533", email: "Smalketbi@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 490, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "إدارة الدعوى", name: "محمد مصبح", phone: "092045534", email: "mmalbedwawi@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 491, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "الإشراف الإداري", name: "سالم دغيش", phone: "092045519", email: "sdalteneiji@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 492, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "التنفيذ", name: "سالم الكتبي", phone: "092045535", email: "Sketbi@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 493, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "التنفيذ", name: "علي الشامسي", phone: "092045525", email: "ahalshamsi@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 494, court: "محكمة دبا الفجيرة الاتحادية الابتدائية", dept: "التنفيذ", name: "محمد القايدي", phone: "092045515", email: "Malqaydi@moj.gov.ae", hours: "", loc: "دبا الفجيرة", source: "ص2 02", em: "الفجيرة" },
  { id: 495, court: "محكمة فلج المعلا الجزئية", dept: "مكتب المحكمة", name: "", phone: "067681444", email: "", hours: "", loc: "فلج المعلا - أم القيوين", source: "11 ص26", em: "أم القيوين" },
  { id: 496, court: "محكمة كلباء الجزئية", dept: "أمين سر", name: "أحمد المازمي", phone: "092778114", email: "", hours: "", loc: "كلباء - الشارقة", source: "11 ص24", em: "الشارقة" },
  { id: 497, court: "محكمة مدام", dept: "مكتب المحكمة", name: "", phone: "068828000", email: "", hours: "", loc: "المدام - الشارقة", source: "11 ص27", em: "الشارقة" }
];
